spring:
#  profiles:
#    active: dev
  # 缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

server:
  port: 8080
  servlet:
    context-path: /sale

c3p0:
    jdbcUrl: jdbc:mysql://localhost:3306/mobile_sale?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    user: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
    minPoolSize: 2
    maxPoolSize: 10
    maxIdleTime: 1800000
    acquireIncrement: 3
    maxStatements: 1000
    initialPoolSize: 3
    idleConnectionTestPeriod: 60
    acquireRetryAttempts: 30
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    testConnectionOnCheckout: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sdu.mobilesale.model

logging:
  level:
    com.sdu.mobilesale: DEBUG

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check