server:
  port: 8080
  servlet:
    context-path: /sale
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/mobile_sale
    name: MobileSale database
    user: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
    acquireIncrement: 11

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sdu.mobilesale.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql