server:
  port: 8080
  servlet:
    context-path: /sale
spring:
  datasource:
    name: MobileSale database
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobile_sale
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml